============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 0 items / 1 error

==================================== ERRORS ====================================
______ ERROR collecting 1089_Duplicate_Zeros/test_1089_Duplicate_Zeros.py ______
ImportError while importing test module '/data/sandeep/leetcode-master/.verifaiws/1089_Duplicate_Zeros/test_1089_Duplicate_Zeros.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
1089_Duplicate_Zeros/test_1089_Duplicate_Zeros.py:3: in <module>
    from .solution import Solution
E   ImportError: attempted relative import with no known parent package
=========================== short test summary info ============================
ERROR 1089_Duplicate_Zeros/test_1089_Duplicate_Zeros.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.04s ===============================
