============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

345_Reverse_Vowels_of_a_String/test_345_Reverse_Vowels_of_a_String.py F  [100%]

=================================== FAILURES ===================================
______________________________ test_reverseVowels ______________________________

    def test_reverseVowels():
>       sol = Solution()
E       NameError: name 'Solution' is not defined

345_Reverse_Vowels_of_a_String/test_345_Reverse_Vowels_of_a_String.py:4: NameError
=========================== short test summary info ============================
FAILED 345_Reverse_Vowels_of_a_String/test_345_Reverse_Vowels_of_a_String.py::test_reverseVowels
============================== 1 failed in 0.01s ===============================
