============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

668_Kth_Smallest_Number_in_Multiplication_Table/test_668_Kth_Smallest_Number_in_Multiplication_Table.py F [100%]

=================================== FAILURES ===================================
_______________________ TestSolution.test_findKthNumber ________________________

self = <test_668_Kth_Smallest_Number_in_Multiplication_Table.TestSolution object at 0x7f196b8f4370>

    def test_findKthNumber(self):
        # Test Case 1
        m, n, k = 3, 3, 5
>       solution = Solution()
E       NameError: name 'Solution' is not defined

668_Kth_Smallest_Number_in_Multiplication_Table/test_668_Kth_Smallest_Number_in_Multiplication_Table.py:7: NameError
=========================== short test summary info ============================
FAILED 668_Kth_Smallest_Number_in_Multiplication_Table/test_668_Kth_Smallest_Number_in_Multiplication_Table.py::TestSolution::test_findKthNumber
============================== 1 failed in 0.01s ===============================
