============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 5 items

674_Longest_Continuous_Increasing_Subsequence/test_674_Longest_Continuous_Increasing_Subsequence.py . [ 20%]
...F                                                                     [100%]

=================================== FAILURES ===================================
_______ TestSolution.test_findLengthOfLCIS_list_with_alternating_values ________

self = <test_674_Longest_Continuous_Increasing_Subsequence.TestSolution object at 0x7fb71a3807f0>

    def test_findLengthOfLCIS_list_with_alternating_values(self):
>       assert Solution().findLengthOfLCIS([1, 3, 2, 4, 3, 5]) == 3
E       assert 2 == 3
E        +  where 2 = <bound method Solution.findLengthOfLCIS of <solution.Solution object at 0x7fb71a380a60>>([1, 3, 2, 4, 3, 5])
E        +    where <bound method Solution.findLengthOfLCIS of <solution.Solution object at 0x7fb71a380a60>> = <solution.Solution object at 0x7fb71a380a60>.findLengthOfLCIS
E        +      where <solution.Solution object at 0x7fb71a380a60> = Solution()

674_Longest_Continuous_Increasing_Subsequence/test_674_Longest_Continuous_Increasing_Subsequence.py:28: AssertionError
=========================== short test summary info ============================
FAILED 674_Longest_Continuous_Increasing_Subsequence/test_674_Longest_Continuous_Increasing_Subsequence.py::TestSolution::test_findLengthOfLCIS_list_with_alternating_values
========================= 1 failed, 4 passed in 0.02s ==========================
