============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 3 items

221_Maximal_Square/test_221_Maximal_Square.py FFF                        [100%]

=================================== FAILURES ===================================
________________________ test_maximalSquare_bruteForce _________________________

    def test_maximalSquare_bruteForce():
>       sol = Solution()
E       NameError: name 'Solution' is not defined

221_Maximal_Square/test_221_Maximal_Square.py:4: NameError
____________________________ test_maximalSquare_dp _____________________________

    def test_maximalSquare_dp():
>       sol = Solution()
E       NameError: name 'Solution' is not defined

221_Maximal_Square/test_221_Maximal_Square.py:21: NameError
_________________________ test_maximalSquare_dp_nSpace _________________________

    def test_maximalSquare_dp_nSpace():
>       sol = Solution()
E       NameError: name 'Solution' is not defined

221_Maximal_Square/test_221_Maximal_Square.py:38: NameError
=========================== short test summary info ============================
FAILED 221_Maximal_Square/test_221_Maximal_Square.py::test_maximalSquare_bruteForce
FAILED 221_Maximal_Square/test_221_Maximal_Square.py::test_maximalSquare_dp
FAILED 221_Maximal_Square/test_221_Maximal_Square.py::test_maximalSquare_dp_nSpace
============================== 3 failed in 0.02s ===============================
