============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

021_Merge_Two_Sorted_Lists/test_021_Merge_Two_Sorted_Lists.py F          [100%]

=================================== FAILURES ===================================
_____________________ TestMergeTwoLists.test_mergeTwoLists _____________________

self = <test_021_Merge_Two_Sorted_Lists.TestMergeTwoLists object at 0x7f482fba0340>

    def test_mergeTwoLists(self):
        # Testcase 1: Both lists are empty
>       solution = Solution()
E       NameError: name 'Solution' is not defined

021_Merge_Two_Sorted_Lists/test_021_Merge_Two_Sorted_Lists.py:6: NameError
=========================== short test summary info ============================
FAILED 021_Merge_Two_Sorted_Lists/test_021_Merge_Two_Sorted_Lists.py::TestMergeTwoLists::test_mergeTwoLists
============================== 1 failed in 0.01s ===============================
